# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: adman_development
  host: localhost
  user: postgres
  password: pg

test:
  adapter: postgresql
  database: adman_test
  host: localhost
  user: postgres
  password: pg

